### ISSUE TITLE
Card 컴포넌트의 마진값 수정

### ISSUE THREAD

**Issue by deli-ght** [Junghoon-P/SPACE_DEV_CLUB_FRONT#25]
# ISSUE
## 종류
ISSUE 종류를 선택하세요
- [x] Code Review
- [ ] New Feature
- [ ] Bug Fix
- [ ] CI / CD
- [ ] Setup

## 제목
- 제목 : Card 컴포넌트의 마진값 수정

## 내용
- 내용 : Card 컴포넌트의 margin-top 값이 없어도 될거같아요.

**Comment by jae04099** [comment]
수정완료하였습니다.
